---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kinda-rocks-v1beta1-database
  failurePolicy: Fail
  name: mdatabase-v1beta1.kb.io
  rules:
  - apiGroups:
    - kinda.rocks
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-kinda-rocks-v1beta1-dbinstance
  failurePolicy: Fail
  name: mdbinstance-v1beta1.kb.io
  rules:
  - apiGroups:
    - kinda.rocks
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbinstances
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kinda-rocks-v1beta1-database
  failurePolicy: Fail
  name: vdatabase-v1beta1.kb.io
  rules:
  - apiGroups:
    - kinda.rocks
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - databases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kinda-rocks-v1beta1-dbinstance
  failurePolicy: Fail
  name: vdbinstance-v1beta1.kb.io
  rules:
  - apiGroups:
    - kinda.rocks
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbinstances
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-kinda-rocks-v1beta1-dbuser
  failurePolicy: Fail
  name: vdbuser-v1beta1.kb.io
  rules:
  - apiGroups:
    - kinda.rocks
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - dbusers
  sideEffects: None
