features:
  existingUser:
    enabled: false
    username: testuser
    password: qwertyu9

postgresql:
  admin:
    password: 123123!!
    user: db-operator
  service:
    name: postgres-instance
    namespace: databases
