apiVersion: "kinda.rocks/v1beta1"
kind: "Database"
metadata:
  name: postgres-db-clone
spec:
  secretName: postgres-db-credentials
  credentials:
    templates:
      - name: CHECK
        template: CHECK
        secret: true
  instance: generic-postgres
  postgres:
    schemas:
      - test
    extensions:
      - pg_stat_statements
  deletionProtected: false
