apiVersion: "kinda.rocks/v1beta1"
kind: "DbUser"
metadata:
  name: postgres-user-$NUM
spec:
  secretName: postgres-readonly-user-$NUM
  accessType: readOnly
  databaseRef: postgres-db
---
apiVersion: "kinda.rocks/v1beta1"
kind: "DbUser"
metadata:
  name: mysql-user-$NUM
spec:
  secretName: mysql-readonly-user-$NUM
  accessType: readOnly
  databaseRef: mysql-db
