name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  product_name: db-operator
  go_os: linux
  go_arch: amd64
  main_go_path: .

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get go version
        run: echo "GO_VERSION=$(make desired-go-version)" >> "${GITHUB_ENV}"
      - name: Setup GO
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Check Code Style
        run: make lint
  
  unit-test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Get go version
        run: echo "GO_VERSION=$(make desired-go-version)" >> "${GITHUB_ENV}"
      - name: Setup GO
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run the unit tests
        run: go test -tags tests -run "TestUnit" ./... -v -cover

  kubernetes-tests:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get go version
        run: echo "GO_VERSION=$(make desired-go-version)" >> "${GITHUB_ENV}"
      - name: Setup GO
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Prepare the test environment
        run: make setup-envtest
      - name: Run the kubernetes integration tests
        run: go test -tags tests -run "TestKubernetes" ./... -v -cover

  mysql-test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      MARIADB_INSTALL: "true"
      MYSQL_PORT: 30306
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: qwertyu9
      CERT_MANAGER_INSTALL: false
    strategy:
      matrix:
        version:
          - MARIADB_VERSION: 12.2
          - MARIADB_VERSION: 11.8
          - MARIADB_VERSION: 10.11
    steps:
      - uses: actions/checkout@v6
      - run: echo "GO_VERSION=$(make desired-go-version)" >> "${GITHUB_ENV}"
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: azure/setup-helm@v4.3.1
      - uses: helm/kind-action@v1.14.0
        with:
          config: ./kind-config.yaml
      - uses: helmfile/helmfile-action@v2.1.0
        with:
          helmfile-auto-init: true
          helmfile-args: sync --wait
      - run: go test -count=1 -tags tests -run "TestMysql" ./... -v -cover

  postgres-test:
    runs-on: ubuntu-latest
    needs: lint
    env:
      POSTGRES_INSTALL: "true"
      POSTGRES_PORT: 30432
      POSRGRES_HOST: localhost
      POSTGRES_USER: db-operator
      POSTGRES_PASSWORD: qwertyu9
      CERT_MANAGER_INSTALL: false
    strategy:
      matrix:
        version:
          - POSTGRES_VERSION: 18
          - POSTGRES_VERSION: 17
          - POSTGRES_VERSION: 16
          - POSTGRES_VERSION: 15
          - POSTGRES_VERSION: 14
    steps:
      - uses: actions/checkout@v6
      - run: echo "GO_VERSION=$(make desired-go-version)" >> "${GITHUB_ENV}"
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: azure/setup-helm@v4.3.1
      - uses: helm/kind-action@v1.14.0
        with:
          config: ./kind-config.yaml
      - uses: helmfile/helmfile-action@v2.1.0
        with:
          helmfile-auto-init: true
          helmfile-args: sync --wait
      - run: go test -count=1 -tags tests -run "TestPostgres" ./... -v -cover
  e2e-tests:
    runs-on: ubuntu-latest
    needs: lint
    env:
      POSTGRES_INSTALL: "true"
      POSTGRES_PORT: 30432
      POSRGRES_HOST: localhost
      POSTGRES_USER: db-operator
      POSTGRES_PASSWORD: qwertyu9
      MARIADB_INSTALL: "true"
      MYSQL_PORT: 30306
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: qwertyu9
      CONTAINER_TOOL: docker
    steps:
      - uses: actions/checkout@v6
      - run: echo "GO_VERSION=$(make desired-go-version)" >> "${GITHUB_ENV}"
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: azure/setup-helm@v4.3.1
      - uses: docker/setup-docker-action@v5
      - uses: helm/kind-action@v1.14.0
        with:
          config: ./kind-config.yaml
          cluster_name: db-operator-kind
      - uses: helmfile/helmfile-action@v2.1.0
        with:
          helmfile-auto-init: true
          helmfile-args: sync --wait
      - run: |-
          make docker-save
          kind load image-archive my-image.tar --name=$(kind get clusters)
          make install
          make deploy
          kubectl rollout -n db-operator-system  status deployment/db-operator-controller-manager -w
          kubectl rollout -n db-operator-system  status deployment/db-operator-controller-webhook -w
      - run: |-
          cd ./test    
          go test ./e2e -v -v ginkgo.v
