name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mysql-test:
    runs-on: ubuntu-latest
    env:
      MARIADB_INSTALL: "true"
      MYSQL_PORT: 30306
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: qwertyu9
      CERT_MANAGER_INSTALL: false
    strategy:
      matrix:
        version:
          - MARIADB_VERSION: 12.2
          - MARIADB_VERSION: 11.8
          - MARIADB_VERSION: 10.11
    steps:
      - uses: actions/checkout@v6
      - uses: go-task/setup-task@v1
      - run: echo "GO_VERSION=$(task desired-go-version)" >> "${GITHUB_ENV}"
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: azure/setup-helm@v5.0.0
      - uses: helm/kind-action@v1.14.0
        with:
          config: ./kind-config.yaml
      - uses: helmfile/helmfile-action@v2.4.1
        with:
          helmfile-auto-init: true
          helmfile-args: sync --wait
      - run: task mysql-test

  postgres-test:
    runs-on: ubuntu-latest
    env:
      POSTGRES_INSTALL: "true"
      POSTGRES_PORT: 30432
      POSRGRES_HOST: localhost
      POSTGRES_USER: db-operator
      POSTGRES_PASSWORD: qwertyu9
      CERT_MANAGER_INSTALL: false
    strategy:
      matrix:
        version:
          - POSTGRES_VERSION: 18
          - POSTGRES_VERSION: 17
          - POSTGRES_VERSION: 16
          - POSTGRES_VERSION: 15
          - POSTGRES_VERSION: 14
    steps:
      - uses: actions/checkout@v6
      - uses: go-task/setup-task@v1
      - run: echo "GO_VERSION=$(task desired-go-version)" >> "${GITHUB_ENV}"
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: azure/setup-helm@v5.0.0
      - uses: helm/kind-action@v1.14.0
        with:
          config: ./kind-config.yaml
      - uses: helmfile/helmfile-action@v2.4.1
        with:
          helmfile-auto-init: true
          helmfile-args: sync --wait
      - run: task postgres-test
